# Generated by Django 5.0.6 on 2024-05-17 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sala",
            fields=[
                ("id_sala", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=100)),
                ("localizacao", models.CharField(max_length=200)),
                ("capacidade", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                ("id_reserva", models.AutoField(primary_key=True, serialize=False)),
                ("reservado_por", models.CharField(max_length=100)),
                ("hora_inicio", models.DateTimeField()),
                ("hora_termino", models.DateTimeField()),
                ("proposito", models.TextField()),
                (
                    "sala",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api_rest.sala"
                    ),
                ),
            ],
        ),
    ]
